### ISSUE TITLE
4 small requests

### ISSUE THREAD

**Issue by GnodabATO** [Alicemetic/nova-drift-cheatsheet#1]
Hi,

There are a few things I'd like to have cleared up with the cheatsheet.

1. With the Drones tree, Grace Protocol and Subsumption's positions should be swapped to align with what's in-game.
2. The MAX icons for the Construct-based Super Mods don't light up when you select a qualifying final-tier Construct mod. They also count as having spent a point if you highlight them yourself.
3. If you can perhaps lock out the other choices when choosing gear, so you don't end up choosing multiple weapons or bodies when that isn't possible. If not, no biggie.
4. Singular Strike's "rate of fire" doesn't list a value; it should be -15%.

That's it! Thanks for making such a great tool.

**Comment by Alicemetic** [comment]
I fixed item 1, 2, and 4
Thanks for reporting!

As for item 3, I think it's worth to allow multiple selections in situations like "any of these gears"
It would be good to prevent mod count from increasing even if multiple selections are made, but it might be a bit troublesome to implement
I'll try it when I have some free time!

**Comment by GnodabATO** [comment]
Great, thanks for taking care of these!

You're right about the "any of these gears will work" situation, I never thought about that. 
Like I said, it's not a huge deal so if it ends up being too complicated don't worry about it.
Thanks again!

**Comment by GnodabATO** [comment]
Found one more issue with Warpath's description. Looks like part of it got cut off. Should be:

"+0.75% total rate of fire and thrust for each stack, up to +30%"

Thanks!

**Comment by Alicemetic** [comment]
fixed!
